Fix a NPE for the stacktrace below
java.lang.RuntimeException: Unable to destroy activity {me.jfenn.alarmio/me.jfenn.alarmio.activities.AlarmActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.AudioManager.setStreamVolume(int, int, int)' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3976)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3994)
	at android.app.ActivityThread.access$1400(ActivityThread.java:179)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1525)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5659)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1018)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:813)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.AudioManager.setStreamVolume(int, int, int)' on a null object reference
	at me.jfenn.alarmio.activities.AlarmActivity.stopAnnoyingness(AlarmActivity.java:229)
	at me.jfenn.alarmio.activities.AlarmActivity.onDestroy(AlarmActivity.java:218)
	at android.app.Activity.performDestroy(Activity.java:6271)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1148)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3963)
	... 10 more